export default class Fonts {
  static Type = {
    GBold: 'Gibson-Bold',
    GBoldItalic: 'Gibson-BoldItalic',
    GRegular: 'Gibson-Regular',
    GSemiboldIt: 'Gibson-SemiBoldItalic',
    GItalic: 'Gibson-Italic',
    GLightIt: 'Gibson-LightItalic',
    GSemiBold: 'Gibson-SemiBold',
    GLight: 'Gibson-Light',
    ABlack: 'Axiforma-Black',
    ABlackItalic: 'Axiforma-BlackItalic',
    ABold: 'Axiforma-Bold',
    ABoldItalic: 'Axiforma-BoldItalic',
    ABook: 'Axiforma-Book',
    ABookItalic: 'Axiforma-BookItalic',
    AExtraBold: 'Axiforma-ExtraBold',
    AExtraBoldItalic: 'Axiforma-ExtraBoldItalic',
    AHeavy: 'Axiforma-Heavy',
    AHeavyItalic: 'Axiforma-HeavyItalic',
    AItalic: 'Axiforma-Italic',
    ALight: 'Axiforma-Light',
    ALightItalic: 'Axiforma-LightItalic',
    AMedium: 'Axiforma-Medium',
    AMediumItalic: 'Axiforma-MediumItalic',
    ARegular: 'Axiforma-Regular',
    ASemiBold: 'Axiforma-SemiBold',
    ASemiBoldItalic: 'Axiforma-SemiBoldItalic',
    AThin: 'Axiforma-Thin',
    AThinItalic: 'Axiforma-ThinItalic',
  };

  static Size = {
    xxxSmall: 11,
    xxSmall: 13,
    xSmall: 14,
    small: 15,
    normal: 17,
    medium: 19,
    large: 21,
    xLarge: 23,
    xxLarge: 28,
    xxxLarge: 31,
    huge: 34,
    xHuge: 37,
    xxHuge: 40,
    xxxHuge: 43,
  };
}
