export default {
  // Tabs
  home: require('../assets/icons/tabIcons/home.png'),
  orders: require('../assets/icons/tabIcons/orders.png'),
  profile: require('../assets/icons/tabIcons/profile.png'),
  settings: require('../assets/icons/tabIcons/settings.png'),
  chat: require('../assets/icons/tabIcons/icChat.png'),
  more: require('../assets/icons/icMore/icMore.png'),
  // Tabs
  clock: require('../assets/icons/clock/clock.png'),
  notification: require('../assets/icons/notification/notification.png'),
  search: require('../assets/icons/search/search.png'),
  LandingPageBackground: require('../assets/images/LandingImage.png'),
  SocialIcons: {
    Facebook: require('../assets/icons/SocialIcons/Facebook.png'),
    Apple: require('../assets/icons/SocialIcons/Apple.png'),
    Google: require('../assets/icons/SocialIcons/Google.png'),
  },
  NavigationIcons: {
    Back: require('../assets/icons/navigation/backButton.png'),
  },
  phone: require('../assets/icons/phone/phone.png'),
  email: require('../assets/icons/email/email.png'),
  location: require('../assets/icons/location/location.png'),
  edit: require('../assets/icons/edit/edit.png'),
  icPrivacy: require('../assets/icons/icPrivacy/icPrivacy.png'),
  icLock: require('../assets/icons/icLock/icLock.png'),
  icFaqs: require('../assets/icons/icFaqs/icFaqs.png'),
  icTerms: require('../assets/icons/icTerms/icTerms.png'),
  icPayment: require('../assets/icons/icPayment/icPayment.png'),
  icbankAccount: require('../assets/icons/bankAccount/bankAccount.png'),
  icRightArrow: require('../assets/icons/icRightArrow/icRightArrow.png'),
  icLeftArrow: require('../assets/icons/icLeftArrow/icLeftArrow.png'),
  icProfile: require('../assets/icons/icProfile/icProfile.png'),
  icAdd: require('../assets/icons/icAdd/icAdd.png'),
  icFilter: require('../assets/icons/icFilter/icFilter.png'),
  icNotification: require('../assets/icons/icNotification/icNotification.png'),
  icPhoneViolet: require('../assets/icons/icPhoneViolet/icPhoneViolet.png'),
  icEmailViolet: require('../assets/icons/icEmailViolet/icEmailViolet.png'),
  icStar: require('../assets/icons/icStar/icStar.png'),
  icChat: require('../assets/icons/icChat/icChat.png'),
  icChatViolet: require('../assets/icons/icChatViolet/icChatViolet.png'),
  icCross: require('../assets/icons/icCross/icCross.png'),
  icCancel: require('../assets/icons/icCross/icCancel.png'),
  icEditWhite: require('../assets/icons/editWhite/icEditWhite.png'),
  icMessage: require('../assets/icons/messege/icMessage.png'),
  icTrash: require('../assets/icons/icTrash/icTrash.png'),
  icTrashCircle: require('../assets/icons/icTrashCircle/icTrashCircle.png'),
  icCalendar: require('../assets/icons/icCalendar/icCalendar.png'),
  icCheckSuccess: require('../assets/icons/icCheckSuccess/icCheckSuccess.png'),
  icMap: require('../assets/images/map.png'),
  icFourStar: require('../assets/images/icFourStar.png'),
  icFiveStar: require('../assets/images/icFiveStar.png'),
  icEditWhiteCircle: require('../assets/icons/icEditWhiteCircle/icEditWhiteCircle.png'),
  icTrashChat: require('../assets/icons/icTrashChat/icTrashChat.png'),
  sendBtn: require('../assets/icons/sendBtn/sendBtn.png'),
  icArrowDropUp: require('../assets/icons/icArrowDropUp/icArrowDropUp.png'),
  icArrowDropLeft: require('../assets/icons/icArrowDropLeft/icArrowDropLeft.png'),
  icArrowDropRight: require('../assets/icons/icArrowDropRight/icArrowDropRight.png'),
  icTick: require('../assets/icons/icTick/icTick.png'),
  icUnTick: require('../assets/icons/icUnTick/icUnTick.png'),
  icAddCard: require('../assets/icons/icAddCard/icAddCard.png'),
  icCheckBox: require('../assets/icons/icCheckBox/icCheckBox.png'),
  icUnCheckBox: require('../assets/icons/icUnCheckBox/icUnCheckBox.png'),

  /// Extra Images
  Visa: require('../assets/images/Visa.png'),
  MasterCard: require('../assets/images/MasterCard.png'),

  icPlaceholder: require('../assets/icons/icPlaceholder/icPlaceholder.png'),
  icPlus: require('../assets/icons/icPlus/icPlus.png'),
  icOpenEye: require('../assets/icons/icOpenEye/icOpenEye.png'),
  icCloseEye: require('../assets/icons/icCloseEye/icCloseEye.png'),
  icImagePicker: require('../assets/icons/icImagePicker/icImagePicker.png'),
  icAddButton: require('../assets/images/addButton.png'),
};
