require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'Presslink' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Pin TOCropViewController to a version compatible with
  # react-native-image-crop-picker 0.37.2 (needs customAspectRatio API)
  pod 'TOCropViewController', '~> 2.6.0'

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['WARNING_CFLAGS'] = ['$(inherited)', '-w']
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-error'

        # Fix for std::unary_function removed in Xcode 15+ (libc++ C++17)
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] += [
          '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION=1',
          '_LIBCPP_DISABLE_AVAILABILITY=1',
        ]
      end
    end
  end
end
